#include "ir_file_generator.h"
#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

// Função para gerar o conteúdo do arquivo .ir
char* generate_ir_file_content(const char* signal_name, const ir_decoded_data_t* decoded) {
    static char buffer[1024];
    
    snprintf(buffer, sizeof(buffer),
        "Filetype: IR signals file\n"
        "Version: 1\n"
        "# Generated by HIGHBOY\n"
        "# \n"
        "name: %s\n"
        "type: parsed\n"
        "protocol: %s\n"
        "address: %02lX %02lX %02lX %02lX\n"
        "command: %02lX %02lX %02lX %02lX\n",
        signal_name,
        decoded->protocol,
        // Endereço formatado em 4 bytes
        (unsigned long)(decoded->address & 0xFF),
        (unsigned long)((decoded->address >> 8) & 0xFF),
        (unsigned long)((decoded->address >> 16) & 0xFF),
        (unsigned long)((decoded->address >> 24) & 0xFF),
        // Comando formatado em 4 bytes
        (unsigned long)(decoded->command & 0xFF),
        (unsigned long)((decoded->command >> 8) & 0xFF),
        (unsigned long)((decoded->command >> 16) & 0xFF),
        (unsigned long)((decoded->command >> 24) & 0xFF)
    );
    
    return buffer;
}

// Função para gerar nome do arquivo baseado no timestamp
void generate_filename(char* filename, size_t size, const char* protocol) {
    // Usa tick count como timestamp simples
    uint32_t timestamp = xTaskGetTickCount();
    snprintf(filename, size, "%s_%lu.ir", protocol, (unsigned long)timestamp);
}

// Função para gerar nome do sinal baseado no protocolo e dados
void generate_signal_name(char* signal_name, size_t size, const char* protocol, const ir_decoded_data_t* decoded) {
    snprintf(signal_name, size, "%s_Signal_%04X_%04X", 
             protocol, 
             (unsigned int)decoded->address, 
             (unsigned int)decoded->command);
}